### ISSUE TITLE
Ansible Configuration failed

### ISSUE THREAD

**Issue by DraGiuS** [zigzag-linux/zigzag-images#1] opened 2018-07-22 16:05 UTC
Hi,
when i try to build zigzag linux (leap or tumbleweed), when running the config.sh, an error occured :

`[ ERROR   ]: 14:17:39 | KiwiScriptFailed: config.sh failed:  [WARNING]: Consider using the file module with state=touch rather than running
touch.  If you need to use command because file is insufficient you can add
warn=False to this command task or set command_warnings=False in ansible.cfg to
get rid of this message.
Traceback (most recent call last):
  File "/usr/bin/zigzag-write-configuration", line 29, in <module>
    subprocess.run(['ansible-playbook', '-i', 'localhost,', '-c', 'local', preset_path], check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ansible-playbook', '-i', 'localhost,', '-c', 'local', '/usr/share/zigzag/ansible/root.yml']' returned non-zero exit status `2.`

:(

**Comment by mkrawiec** [comment] 2018-07-22 20:47
Hey, DraGiuS I'm pretty impressed that somebody found this project ;)

The output of the build command doesn't tell much about the cause of the problem, can you post the end of `out/build/image-root.log`, it will have some more details of what exactly failed.

**Comment by DraGiuS** [comment] 2018-07-22 20:55
So here the output of image-root-log :

> DEBUG: failed: [localhost] (item=['chromium-plugin-widevinecdm', 'vlc-codecs', 'vlc-vdpau']) => {"changed": false, "cmd": ["/usr/bin/zypper", "--quiet", "--non-interactive", "--xmlout", "install", "--type", "package", "--auto-agree-with-licenses", "--no-recommends", "--", "+chromium-plugin-widevinecdm", "+vlc-codecs", "+vlc-vdpau"], "item": ["chromium-plugin-widevinecdm", "vlc-codecs", "vlc-vdpau"], "msg": "Zypper run command failed with return code 4.", "rc": 4, "stderr": "", "stderr_lines": [], "stdout": "<?xml version='1.0'?>\n<stream>\n<prompt id=\"1\">\n<description>Problem: vlc-codecs-3.0.3-5.3.x86_64 requires libavcodec58(unrestricted), but this requirement cannot be provided\n  not installable providers: libavcodec58-4.0.1-4.1.i586[packman-essentials]\n                   libavcodec58-4.0.1-4.1.x86_64[packman-essentials]\n Solution 1: Following actions will be done:\n  install libavcodec58-4.0.1-4.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n  install libavformat58-4.0.1-4.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n  install libavfilter7-4.0.1-4.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n  install libavdevice58-4.0.1-4.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n Solution 2: do not install vlc-codecs-3.0.3-5.3.x86_64\n Solution 3: break vlc-codecs-3.0.3-5.3.x86_64 by ignoring some of its dependencies\n</description>\n<text>Choose from above solutions by number or skip, retry or cancel</text>\n<option value=\"1\" desc=\"\"/>\n<option value=\"2\" desc=\"\"/>\n<option value=\"3\" desc=\"\"/>\n<option value=\"s\" desc=\"\"/>\n<option value=\"r\" desc=\"\"/>\n<option default=\"1\" value=\"c\" desc=\"\"/>\n</prompt>\n</stream>\n", "stdout_lines": ["<?xml version='1.0'?>", "<stream>", "<prompt id=\"1\">", "<description>Problem: vlc-codecs-3.0.3-5.3.x86_64 requires libavcodec58(unrestricted), but this requirement cannot be provided", "  not installable providers: libavcodec58-4.0.1-4.1.i586[packman-essentials]", "                   libavcodec58-4.0.1-4.1.x86_64[packman-essentials]", " Solution 1: Following actions will be done:", "  install libavcodec58-4.0.1-4.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", "  install libavformat58-4.0.1-4.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", "  install libavfilter7-4.0.1-4.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", "  install libavdevice58-4.0.1-4.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", " Solution 2: do not install vlc-codecs-3.0.3-5.3.x86_64", " Solution 3: break vlc-codecs-3.0.3-5.3.x86_64 by ignoring some of its dependencies", "</description>", "<text>Choose from above solutions by number or skip, retry or cancel</text>", "<option value=\"1\" desc=\"\"/>", "<option value=\"2\" desc=\"\"/>", "<option value=\"3\" desc=\"\"/>", "<option value=\"s\" desc=\"\"/>", "<option value=\"r\" desc=\"\"/>", "<option default=\"1\" value=\"c\" desc=\"\"/>", "</prompt>", "</stream>"]}
DEBUG: 	to retry, use: --limit @/usr/share/zigzag/ansible/root.retry
DEBUG: PLAY RECAP *********************************************************************
DEBUG: localhost                  : ok=38   changed=31   unreachable=0    failed=1   
DEBUG: --------------out stop--------------
DEBUG: --------------err start-------------
DEBUG:  [WARNING]: Consider using the file module with state=touch rather than running
touch.  If you need to use command because file is insufficient you can add
warn=False to this command task or set command_warnings=False in ansible.cfg to
get rid of this message.
Traceback (most recent call last):
  File "/usr/bin/zigzag-write-configuration", line 29, in <module>
    subprocess.run(['ansible-playbook', '-i', 'localhost,', '-c', 'local', preset_path], check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ansible-playbook', '-i', 'localhost,', '-c', 'local', '/usr/share/zigzag/ansible/root.yml']' returned non-zero exit status 2.

> --------------err stop--------------
ERROR: KiwiScriptFailed: config.sh failed:  [WARNING]: Consider using the file module with state=touch rather than running
touch.  If you need to use command because file is insufficient you can add
warn=False to this command task or set command_warnings=False in ansible.cfg to
get rid of this message.
Traceback (most recent call last):
  File "/usr/bin/zigzag-write-configuration", line 29, in <module>
    subprocess.run(['ansible-playbook', '-i', 'localhost,', '-c', 'local', preset_path], check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ansible-playbook', '-i', 'localhost,', '-c', 'local', '/usr/share/zigzag/ansible/root.yml']' returned non-zero exit status 2.

> INFO: Cleaning up SystemPrepare instance
DEBUG: EXEC: [mountpoint /kiwi/out/build/image-root/kiwi/out/cache]
DEBUG: EXEC: [mountpoint /kiwi/out/build/image-root/kiwi/out/cache]
DEBUG: EXEC: [umount -l /kiwi/out/build/image-root/kiwi/out/cache]
DEBUG: EXEC: [mountpoint /kiwi/out/build/image-root/sys]
DEBUG: EXEC: [mountpoint /kiwi/out/build/image-root/sys]
DEBUG: EXEC: [umount -l /kiwi/out/build/image-root/sys]
DEBUG: EXEC: [mountpoint /kiwi/out/build/image-root/dev]
DEBUG: EXEC: [mountpoint /kiwi/out/build/image-root/dev]
DEBUG: EXEC: [umount -l /kiwi/out/build/image-root/dev]
DEBUG: EXEC: [mountpoint /kiwi/out/build/image-root/proc]
DEBUG: EXEC: [mountpoint /kiwi/out/build/image-root/proc]
DEBUG: EXEC: [umount -l /kiwi/out/build/image-root/proc]
DEBUG: EXEC: [rmdir --ignore-fail-on-non-empty /kiwi/out/build/image-root/kiwi/out/cache]
DEBUG: EXEC: [rmdir --ignore-fail-on-non-empty /kiwi/out/build/image-root/kiwi/out]
DEBUG: EXEC: [rmdir --ignore-fail-on-non-empty /kiwi/out/build/image-root/kiwi]
DEBUG: EXEC: [rmdir --ignore-fail-on-non-empty /kiwi/out/build/image-root]
DEBUG: EXEC: [rmdir --ignore-fail-on-non-empty /kiwi/out/build]
DEBUG: EXEC: [rmdir --ignore-fail-on-non-empty /kiwi/out]
DEBUG: EXEC: [rmdir --ignore-fail-on-non-empty /kiwi]
DEBUG: EXEC: Failed with stderr: rmdir: failed to remove '/kiwi'

**Comment by mkrawiec** [comment] 2018-07-22 21:26
That looks like packman is not keeping up with the changes in upsteam opensuse, should be only temporary issue.

You can try adding `export ZIGZAG_OSS_ONLY=1` to `config.sh` and running a fresh build.

**Comment by DraGiuS** [comment] 2018-07-22 23:26
The error is still present even using this thing :(

**Comment by mkrawiec** [comment] 2018-07-25 20:02
I finally had some time to tinker with the `tumbleweed-devel` build. It was failing due to recent switch to python3 for ansible in Tumbleweed repos. I pushed some workarounds and it should be building now.  BTW no issues related to packman for me.

That's the primary reason I mostly focus on `leap-devel` and `leap-stable`, since they are stable enough to give working builds most of the time.

**Comment by DraGiuS** [comment] 2018-07-25 20:16
The builds that i tried was on leap-devel. I'll try with tumbleweed-devel.

**Comment by DraGiuS** [comment] 2018-07-25 22:03
still dont work :(

**Comment by DraGiuS** [comment] 2018-08-21 19:18
Switched to gentoo, now it works !

**Comment by DraGiuS** [comment] 2018-08-24 21:07
Update... It doesn't work anymore, still having the same issue.
Can you send me an testing iso (if you can) at christophe.ribots@gmail.com ?
Thanks

**Comment by mkrawiec** [comment] 2018-08-31 15:33
The same bug recently started on my end as well, it was the conflict between `ffmpeg-3` required by `vlc-codecs` and `ffmpeg-4` declared in the playbook. You can try building `leap-devel`.

**Comment by DraGiuS** [comment] 2018-08-31 21:33
Still dont work

**Comment by mkrawiec** [comment] 2018-09-01 11:35
Please check the logs, is it the same issue with vlc or a different one?

**Comment by DraGiuS** [comment] 2018-09-01 12:22
`DEBUG: failed: [localhost] (item=[u'chromium-plugin-widevinecdm', u'vlc-codecs', u'vlc-vdpau']) => {"changed": false, "cmd": ["/usr/bin/zypper", "--quiet", "--non-interactive", "--xmlout", "install", "--type", "package", "--auto-agree-with-licenses", "--no-recommends", "--", "+chromium-plugin-widevinecdm", "+vlc-codecs", "+vlc-vdpau"], "item": ["chromium-plugin-widevinecdm", "vlc-codecs", "vlc-vdpau"], "msg": "Zypper run command failed with return code 4.", "rc": 4, "stderr": "", "stderr_lines": [], "stdout": "<?xml version='1.0'?>\n<stream>\n<prompt id=\"1\">\n<description>Problem: vlc-codecs-3.0.2-lp150.3.2.x86_64 requires libavcodec57(unrestricted), but this requirement cannot be provided\n  not installable providers: libavcodec57-3.4.4-lp150.9.1.x86_64[packman-essentials]\n Solution 1: Following actions will be done:\n  install libavcodec57-3.4.4-lp150.9.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n  install libavdevice57-3.4.4-lp150.9.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n  install libavfilter6-3.4.4-lp150.9.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n  install ffmpeg-3-3.4.4-lp150.9.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n  install libavutil55-3.4.4-lp150.9.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n  install libswresample2-3.4.4-lp150.9.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n  install libpostproc54-3.4.4-lp150.9.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n  install libswscale4-3.4.4-lp150.9.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n  install libavresample3-3.4.4-lp150.9.1.x86_64 (with vendor change)\n    openSUSE  --&gt;  http://packman.links2linux.de\n Solution 2: do not install vlc-codecs-3.0.2-lp150.3.2.x86_64\n Solution 3: break vlc-codecs-3.0.2-lp150.3.2.x86_64 by ignoring some of its dependencies\n</description>\n<text>Choose from above solutions by number or skip, retry or cancel</text>\n<option value=\"1\" desc=\"\"/>\n<option value=\"2\" desc=\"\"/>\n<option value=\"3\" desc=\"\"/>\n<option value=\"s\" desc=\"\"/>\n<option value=\"r\" desc=\"\"/>\n<option default=\"1\" value=\"c\" desc=\"\"/>\n</prompt>\n</stream>\n", "stdout_lines": ["<?xml version='1.0'?>", "<stream>", "<prompt id=\"1\">", "<description>Problem: vlc-codecs-3.0.2-lp150.3.2.x86_64 requires libavcodec57(unrestricted), but this requirement cannot be provided", "  not installable providers: libavcodec57-3.4.4-lp150.9.1.x86_64[packman-essentials]", " Solution 1: Following actions will be done:", "  install libavcodec57-3.4.4-lp150.9.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", "  install libavdevice57-3.4.4-lp150.9.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", "  install libavfilter6-3.4.4-lp150.9.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", "  install ffmpeg-3-3.4.4-lp150.9.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", "  install libavutil55-3.4.4-lp150.9.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", "  install libswresample2-3.4.4-lp150.9.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", "  install libpostproc54-3.4.4-lp150.9.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", "  install libswscale4-3.4.4-lp150.9.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", "  install libavresample3-3.4.4-lp150.9.1.x86_64 (with vendor change)", "    openSUSE  --&gt;  http://packman.links2linux.de", " Solution 2: do not install vlc-codecs-3.0.2-lp150.3.2.x86_64", " Solution 3: break vlc-codecs-3.0.2-lp150.3.2.x86_64 by ignoring some of its dependencies", "</description>", "<text>Choose from above solutions by number or skip, retry or cancel</text>", "<option value=\"1\" desc=\"\"/>", "<option value=\"2\" desc=\"\"/>", "<option value=\"3\" desc=\"\"/>", "<option value=\"s\" desc=\"\"/>", "<option value=\"r\" desc=\"\"/>", "<option default=\"1\" value=\"c\" desc=\"\"/>", "</prompt>", "</stream>"]}`

**Comment by mkrawiec** [comment] 2018-09-01 16:03
I don't understand, this is the exact same issue that my last commit to `zigzag-configuration` fixed. Maybe there is some caching on your side, be sure to `sudo rm -fr out/` and build from scratch.

**Comment by DraGiuS** [comment] 2018-09-02 16:55
Yeah, still the same error ..

**Comment by DraGiuS** [comment] 2018-11-02 18:29
If you can maybe you can host a testing iso, can't build anything atm.

**Comment by DraGiuS** [comment] 2018-11-23 13:29
Maybe replacing vlc with mpv would fix that.

**Comment by mkrawiec** [comment] 2020-01-01 16:41
Closing, as some time passed an I still cannot reproduce the issue.

**Closed as completed by mkrawiec** 2020-01-01 16:41 UTC
